# Generated by Django 4.0.3 on 2022-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='film/posters/%Y/%m/%d/', verbose_name='Poster'),
        ),
    ]
